---
- hosts: 172.31.43.52
  become: yes
  tasks:
        - name: i want to install apache2 on ubuntu-node2
          apt:
            name: apache2
            state: absent
          when: ansible_os_family == "Debian"
