---
- hosts: 172.31.43.71
  become: yes
  tasks:
        - name: i want to install tree
          apt:
                name: tree
                state: present
          tags: mytreetask


        - name: i want to install apache2
          apt: 
                name: apache2
                state: present
          tags: myapache2task

        
        - name: i want to install git
          apt:
                name: git
                state: present
          tags: mygittask
