---
- hosts: webserver
  become: yes
  tasks:
        - name: i want to install apache2 on ubuntu
          apt:
                name: "{{apache2onubuntu}}"
                state: present 
          when: ansible_os_family == "Debian"

        - name: i want to install apache2 on redhat
          yum:
                name: "{{apache2onredhat}}"
                state: present
          when: ansible_os_family == "RedHat"
              