---
# tasks file for mywebrole
       - name: i want to install apache2 on ubuntu-node1
         apt:
            name: apache2
            state: present
         when: "'ubuntu' in ansible_distribution and inventory_hostname in groups['ubuntu_server']"


       - name: i want to install nginx on ubuntu-node2
         apt:
            name: nginx
            state: present
         when: "'ubuntu' in ansible_distribution and inventory_hostname in groups['ubuntu_server']"

       - name: i want to install apache2 on redhat-node3
         yum:
            name: httpd
            state: present
         when: "'redhat' in ansible_distribution"
    