---
# tasks file for mywebrole
       - name: i want to install apache2 on ubuntu-node1
         apt:
            name: apache2
            state: present
         when: "ansible_os_family == 'Debian' and inventory_hostname in groups['server1']"


       - name: i want to install nginx on ubuntu-node2
         apt:
            name: nginx
            state: present
         when: "ansible_os_family == 'Debian' and inventory_hostname in groups['server2']"

       - name: i want to install apache2 on redhat-node3
         yum:
            name: httpd
            state: present
         when: ansible_os_family == "RedHat"
    